[Reference](https://blog.devgenius.io/must-know-functions-for-pandas-time-series-data-abc84d957650)

# Setup Pandas Time-Series data from Yahoo Finance

In [2]:
!pip install yfinance

Collecting yfinance
  Downloading yfinance-0.1.67-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.10)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.19.5)
Collecting lxml>=4.5.1
  Downloading lxml-4.6.4-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.3 MB)
     |████████████████████████████████| 6.3 MB 18.7 MB/s
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.1.5)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.7/dist-packages (from yfinance) (2.23.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->yfinance) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->yfinance) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance) (1.15.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (2021.10.8)
Installing collected packages: lxml, yfinance
  Attempting uninstall: lxml
    Found existing installation: lxml 4.2.6
    Uninstalling lxml-4.2.6:
      Successfully uninstalled lxml-4.2.6
Successfully installed lxml-4.6.4 yfinance-0.1.67

In [3]:
import yfinance as yf
df = yf.download("AAPL", interval="5m", period="60d")

[*********************100%***********************]  1 of 1 completed

# Select rows from specific daily intervals

In [4]:
df.between_time("09:30", "09:45")["High"]

Datetime
2021-09-17 09:30:00-04:00    148.470001
2021-09-17 09:35:00-04:00    147.919907
2021-09-17 09:40:00-04:00    147.889999
2021-09-17 09:45:00-04:00    147.589996
2021-09-20 09:30:00-04:00    144.839996
                                ...
2021-12-09 09:45:00-05:00    176.729996
2021-12-10 09:30:00-05:00    176.100006
2021-12-10 09:35:00-05:00    176.556000
2021-12-10 09:40:00-05:00    176.449997
2021-12-10 09:45:00-05:00    176.359894
Name: High, Length: 240, dtype: float64

In [5]:
df.at_time("09:30")

                                 Open        High  ...   Adj Close    Volume
Datetime                                           ...
2021-09-17 09:30:00-04:00  148.339996  148.470001  ...  147.880005  15274089
2021-09-20 09:30:00-04:00  143.750000  144.839996  ...  144.330093   9936431
2021-09-21 09:30:00-04:00  143.929993  144.110001  ...  143.354095   5081881
2021-09-22 09:30:00-04:00  144.449997  144.889999  ...  143.845001   3630008
2021-09-23 09:30:00-04:00  146.649994  146.750000  ...  145.830002   5146912
2021-09-24 09:30:00-04:00  145.770004  146.039993  ...  145.919907   3962003
2021-09-27 09:30:00-04:00  145.470001  145.960007  ...  144.239899   6084187
2021-09-28 09:30:00-04:00  143.500000  143.740005  ...  143.100006   6291667
2021-09-29 09:30:00-04:00  142.470001  143.210007  ...  143.169907   4953269
2021-09-30 09:30:00-04:00  143.660004  144.219894  ...  144.000000   3231709
2021-10-01 09:30:00-04:00  141.899994  142.039993  ...  140.759995   5853061
2021-10-04 09:30:00-04:00  141.750000  142.210007  ...  141.271606   3800241
2021-10-05 09:30:00-04:00  140.000000  140.399994  ...  139.919998   4325117
2021-10-06 09:30:00-04:00  139.470001  139.660004  ...  139.380005   5382152
2021-10-07 09:30:00-04:00  143.089996  143.659897  ...  143.568802   4576790
2021-10-08 09:30:00-04:00  144.029999  144.178101  ...  143.360001   3778345
2021-10-11 09:30:00-04:00  142.270004  142.930298  ...  142.869995   4632151
2021-10-12 09:30:00-04:00  142.875000  143.149994  ...  142.970001   4124784
2021-10-13 09:30:00-04:00  141.235001  141.399994  ...  140.490005   5722917
2021-10-14 09:30:00-04:00  142.110001  142.339996  ...  141.994995   4552704
2021-10-15 09:30:00-04:00  143.770004  144.179993  ...  143.720001   6232522
2021-10-18 09:30:00-04:00  143.445007  143.860001  ...  143.399994   7348892
2021-10-19 09:30:00-04:00  146.839996  147.389999  ...  147.199997   4814449
2021-10-20 09:30:00-04:00  149.000000  149.289993  ...  149.010406   3829632
2021-10-21 09:30:00-04:00  149.386795  149.479996  ...  149.059998   3084434
2021-10-22 09:30:00-04:00  149.690002  149.750000  ...  149.445007   3290844
2021-10-25 09:30:00-04:00  149.160202  149.369995  ...  148.929901   3164588
2021-10-26 09:30:00-04:00  149.339996  149.740005  ...  149.699997   3361931
2021-10-27 09:30:00-04:00  149.375000  149.550003  ...  148.929993   3081418
2021-10-28 09:30:00-04:00  149.820007  150.679993  ...  150.600006   5116476
2021-10-29 09:30:00-04:00  147.214996  148.699997  ...  147.149994  10917117
2021-11-01 09:30:00-04:00  149.250000  149.580002  ...  149.429993  10320406
2021-11-02 09:30:00-04:00  149.039993  149.559998  ...  149.080002   3708540
2021-11-03 09:30:00-04:00  150.598007  150.612900  ...  150.172394   2903352
2021-11-04 09:30:00-04:00  151.429993  152.009995  ...  152.009995   3648712
2021-11-05 09:30:00-04:00  151.889999  152.190002  ...  151.683105   3965809
2021-11-08 09:30:00-05:00  151.410004  151.570007  ...  151.130005   6254058
2021-11-09 09:30:00-05:00  150.199997  150.800003  ...  150.264999   4854071
2021-11-10 09:30:00-05:00  150.020004  150.130005  ...  148.320007   5819670
2021-11-11 09:30:00-05:00  148.679993  149.429993  ...  148.360001   3221503
2021-11-12 09:30:00-05:00  148.429993  148.500000  ...  147.789993   2628732
2021-11-15 09:30:00-05:00  150.369995  151.429993  ...  151.320007   3888100
2021-11-16 09:30:00-05:00  149.940002  150.389999  ...  149.759995   2805609
2021-11-17 09:30:00-05:00  150.994995  151.949997  ...  151.925003   3686372
2021-11-18 09:30:00-05:00  153.710007  154.000000  ...  153.279999  16796198
2021-11-19 09:30:00-05:00  157.649994  157.869995  ...  157.119995  10681846
2021-11-22 09:30:00-05:00  162.339996  163.029999  ...  162.760101  10216478
2021-11-23 09:30:00-05:00  161.119995  161.800003  ...  159.720001   6701737
2021-11-24 09:30:00-05:00  160.750000  161.389999  ...  160.460007   3873181
2021-11-26 09:30:00-05:00  159.565002  160.449997  ...  160.259995   5540326
2021-11-29 09:30:00-05:00  159.656601  160.089996  ...  159.580002   6244089
2021-11-30 09:30:00-05:00  159.985001  160.789993  ...  160.449997   4380808
2021-12-01 09:30:00-05:00  166.839996  167.095901  ...  166.178207   9403885
2021-12-02 09:30:00-05:00  159.000000  160.250000  ...  159.279999  14698959
2021-12-03 09:30:00-05:00  164.020004  164.960007  ...  164.490005   5355257
2021-12-06 09:30:00-05:00  165.309998  165.639999  ...  165.169998   7966012
2021-12-07 09:30:00-05:00  169.080002  169.470001  ...  169.229996   7060639
2021-12-08 09:30:00-05:00  172.125000  172.270004  ...  171.360001   6049974
2021-12-09 09:30:00-05:00  174.910004  176.557297  ...  176.539993   7170068
2021-12-10 09:30:00-05:00  175.205002  176.100006  ...  176.050003   5340182

[60 rows x 6 columns]

# Select rows based on dates

In [7]:
df.loc["2021-09-01":]

                                 Open        High  ...   Adj Close    Volume
Datetime                                           ...
2021-09-17 09:30:00-04:00  148.339996  148.470001  ...  147.880005  15274089
2021-09-17 09:35:00-04:00  147.880005  147.919907  ...  147.669998   2187532
2021-09-17 09:40:00-04:00  147.660004  147.889999  ...  147.470001   2333168
2021-09-17 09:45:00-04:00  147.475006  147.589996  ...  147.320007   2660173
2021-09-17 09:50:00-04:00  147.300003  147.419998  ...  147.179993   1286761
...                               ...         ...  ...         ...       ...
2021-12-10 15:35:00-05:00  178.259995  178.410004  ...  178.179993   1306557
2021-12-10 15:40:00-05:00  178.179993  178.354996  ...  178.339996   2017996
2021-12-10 15:45:00-05:00  178.330002  178.485001  ...  178.460007   2336628
2021-12-10 15:50:00-05:00  178.470001  179.080002  ...  179.059998   3164603
2021-12-10 15:55:00-05:00  179.070007  179.630005  ...  179.500000   5143007

[4645 rows x 6 columns]

# Select rows based on monthly seasonality

In [8]:
import yfinance as yf
df = yf.download("AAPL", interval="1d", period="5Y")

[*********************100%***********************]  1 of 1 completed

In [9]:
df.loc[df.index.month == 12]["High"]

Date
2016-12-12    115.000000
2016-12-13    115.919998
2016-12-14    116.199997
2016-12-15    116.730003
2016-12-16    116.500000
                 ...
2021-12-06    167.879898
2021-12-07    171.580002
2021-12-08    175.960007
2021-12-09    176.750000
2021-12-10    179.630005
Name: High, Length: 104, dtype: float64